name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      # - name: restore h2o binary
      #   uses: actions/cache@v3
      #   with:
      #     path: .github/h2o
      #     key: ${{ runner.os }}-h2o-${{ hashFiles('.github/install-h2o.sh') }}

      - name: restore nginx binary
        uses: actions/cache@v3
        with:
          path: .github/nginx
          key: ${{ runner.os }}-nginx-${{ hashFiles('.github/install-nginx.sh') }}

      # FIXME: h2o doesn't work with OpenSSL v3.
      # - name: install h2o for test
      #   run: .github/install-h2o.sh

      - name: install nginx for test
        run: .github/install-nginx.sh

      - name: download dependencies
        run: go mod download
      - name: Test
        run: |
          make test

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Check GoReleaser configure
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check
