name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: restore go.mod cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: restore h2o binary
        uses: actions/cache@v2
        with:
          path: .github/h2o
          key: ${{ runner.os }}-h2o-${{ hashFiles('.github/install-h2o.sh') }}

      - name: restore nginx binary
        uses: actions/cache@v2
        with:
          path: .github/nginx
          key: ${{ runner.os }}-nginx-${{ hashFiles('.github/install-nginx.sh') }}

      - name: install h2o for test
        run: .github/install-h2o.sh
      - name: install nginx for test
        run: .github/install-nginx.sh

      - name: download dependencies
        run: go mod download
      - name: Test
        run: |
          make test

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Check GoReleaser configure
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
